# Use an official Jupyter Notebook image as the base image
FROM jupyter/base-notebook:latest

# Set the working directory
WORKDIR /home/jovyan/app

# Copy only the requirements file to leverage caching
COPY requirements.txt /home/jovyan/app/requirements.txt

# Copy the local app code into the container
COPY . /home/jovyan/app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /home/jovyan/app/requirements.txt

# Make port 8888 available to the world outside this container
EXPOSE 8888

# Run Jupyter Notebook
CMD ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''"]