name: Tests

on:
  push:
    branches:
      - main
      - githubActionsbranch
  pull_request:
    branches: 
      - main
      - githubActionsbranch


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        anki-version: ["23.12.1"]
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb qt6-base-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-xvfb pytest-forked
        pip install anki==${{ matrix.anki-version }}
        pip install aqt==${{ matrix.anki-version }}
        pip install pytest-anki
        pip install -r requirements.txt

    - name: Set up config
      run: |
        cat > addon/config.json << EOL
        {
            "openrouter_api_key": "${{ secrets.OPENROUTER_API_KEY }}",
            "notion_api_key": "${{ secrets.NOTION_API_KEY }}"
        }
        EOL

    - name: Run tests
      run: |
        pytest tests/ -v --forked --workflow-config=tests/workflow_test_configs/test_url_sources_notes2flash_workflow_config.yml
